apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mosquitto-config
  labels:
    app: mosquitto
data:
  mosquitto.conf: |
    listener 1883 0.0.0.0
    allow_anonymous true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: {{ .Values.mosquitto.image }}
        ports:
        - containerPort: {{ .Values.mosquitto.port }}
          name: mqtt
        volumeMounts:
        - name: config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-mosquitto-config
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  ports:
  - port: {{ .Values.mosquitto.port }}
    targetPort: mqtt
    name: mqtt
  selector:
    app: mosquitto
